### PR TITLE
Feature/user auth

### PR DESCRIPTION
**Pull request by jinyung2**
- Implemented Context API for Auth Context
- Implemented storing of token, user and expTime in localStorage (10 mins)
- Fixed initial app launch redirection issue
- renamed and reordered routes on App.js, implemented auth context `isLoggedIn` status for route protection
- implemented calls to `/signin` and `/signup` api endpoints and redirection based on success + error handling

### CODE REVIEW

**Comment by jinyung2** [comment]
Let's try using a squash and merge on this one, I wanna see what that looks like on GH.

Also, I branched this off the `feature/graph_js` branch and it looks like it has all the same changes as the previous branch did in the last commit. But no conflicts so :partying_face:

**Review by WeslyOrtega — APPROVED** [review]
Looks great!

**Comment by Hadiasemi** [comment]
Looks good to me

**Review by Hadiasemi — APPROVED** [review]
Looks good to me

**Review by tessa-tapmongkol — APPROVED** [review]
Looks good to me!

**Pull request merged**
